[build]
command = 'hugo --gc '
publish = 'public'

[build.environment]
HUGO_VERSION = '0.160.1'

[context.production.environment]
HUGO_ENV = 'production'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL --gc '

[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL --gc '
